spring.application.name=life-tracker
spring.datasource.url=jdbc:postgresql://dpg-d8hhmuflk1mc73ei0vi0-a.oregon-postgres.render.com/life_tracker_v5g4?sslmode=require
spring.datasource.username=life_tracker_v5g4_user
spring.datasource.password=QtQqfQdGUnuXbi68EdPzP1bNgAP4u2Qa
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
server.port=8080